#fourth_robot:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  four_wheel_steering_controller:
    type        : "four_wheel_steering_controller/FourWheelSteeringController"
    front_wheel: ['front_right_wheel_link', 'front_left_wheel_link']
    rear_wheel: ['rear_right_wheel_link', 'rear_left_wheel_link']
    front_steering: ['front_left_steering', 'front_right_steering']
    rear_steering: ['rear_left_steering', 'rear_right_steering']
    publish_rate: 50.0
    pose_covariance_diagonal : [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
    twist_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
    cmd_vel_timeout: 25.0 # not tested here

    # Wheel separation and diameter. These are both optional.
    # diff_drive_controller will attempt to read either one or both from the
    # URDF if not specified as a parameter
    wheel_separation : 1.9
    track : 1.9
    wheel_base : 2.8
    wheel_radius : 0.36
    wheel_steering_y_offset : 0.05

    # Wheel separation and radius multipliers
    wheel_separation_multiplier: 1.0
    wheel_radius_multiplier    : 1.0

    # Velocity commands timeout [s], default 0.5
    cmd_vel_timeout: 1.0
    
    # Base frame_id
    base_frame_id: base_footprint 

    # Velocity and acceleration limits
    # Whenever a min_* is unspecified, default to -max_*
    linear:
      x:
        has_velocity_limits    : true
        max_velocity           : 10.0  # m/s
        min_velocity           : -1.667 # m/s
        has_acceleration_limits: true
        max_acceleration       : 10.0  # m/s^2
        min_acceleration       : -1.0 # m/s^2
    angular:
      z:
        has_velocity_limits    : true
        max_velocity           : 10  # rad/s
        min_velocity           : -3.14
        has_acceleration_limits: true
        max_acceleration       : 10  # rad/s^2
        min_acceleration       : -1.0




